name: 01 - PR mesclado na master

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build_and_test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore VotaE_API.sln

      - name: Limpar projeto
        run: dotnet clean VotaE_API.sln

      - name: Build
        run: dotnet build VotaE_API.sln --configuration Release --no-restore

      - name: Testes
        run: dotnet test VotaE_API.sln --no-build --verbosity normal
