name: 02 - PR mesclado na master

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build_dotnet_project:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Testes
        run: dotnet test --no-build --verbosity normal
