name: continuous-delivery

on:
  push:
    branches: ["release/**"]

env:
  IMAGE_NAME: vota-e-cidade-inteligente
  AZURE_WEBAPP_NAME: vota-e-stg

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências da solution
        run: dotnet restore VotaE_API/VotaE_API.sln

      - name: Build da solution
        run: dotnet build VotaE_API/VotaE_API.sln --configuration Release

      - name: Testes
        run: dotnet test VotaE_API/VotaE_API.sln --verbosity normal

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: VotaE_API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

