name: 02 - PR mesclado na develop

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  build_and_test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências da aplicação
        run: dotnet restore VotaE_API/VotaE_API.csproj

      - name: Build da aplicação
        run: dotnet build VotaE_API/VotaE_API.csproj --configuration Release

      - name: Build da solution
        run: dotnet build VotaE_API.sln --configuration Release

      - name: Testes
        run: dotnet test VotaE_API.sln --no-build --verbosity normal
